service: fastapi-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-1

functions:
  healthCheck:
    timeout: 900
    handler: wsgi_handler.handler
    events:
      - http:
          path: health
          method: get
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin 

custom:
  wsgi:
    app: app.main.app
    packRequirements: false  # Changed to false, let serverless-python-requirements handle packaging

  pythonRequirements:
    dockerizePip: true
    noDeploy:
      - annotated_types  # Use noDeploy instead of exclude for packages
    slim: true  # Reduces package size

package:
  individually: true
  exclude:
    - node_modules/**
    - '**/__pycache__/**'
    - 'backend/.requirements/annotated_types/**'
    - 'backend/.requirements/pydantic/v1/annotation_types.py'  # Exclude the second conflicting file