service: fastapi-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  deploymentBucket:
    name: peanut-butter-serverless-deployment-bucket

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 900
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin 

custom:
  wsgi:
    app: app.main.app
    packRequirements: false

  pythonRequirements:
    dockerizePip: true
    noDeploy:
      - annotated_types
    slim: true  # Reduces package size

package:
  individually: true
  exclude:
    - node_modules/**
    - '**/__pycache__/**'
    - 'backend/.requirements/annotated_types/**'
    - 'backend/.requirements/pydantic/v1/annotation_types.py'  # Exclude the second conflicting file
    - '**/*.venv/**'
    - '**/venv/**'